### ISSUE TITLE
Rancher NFS / Network managed / Multiple Host

### ISSUE THREAD

**Issue by gregori-goossens** [sjiveson/nfs-server-alpine#11]
Hi,

i use your nfs-server-alpine in Rancher infrastructure like below : 
 - Server Data on RancherOS  (with kernel header)  - with your docker image started with Rancher managed network (with fixed docker ip : 10.42.x.x).

- Server Host (with several apps using rancher nfs volume) : Running Rancher NFS Driver targeting 10.42.x.x.

Every thing work fine, until i use a rancher volume on an another host. For exemple, if i add a 2nd host server and launch a new app with new rancher nfs volume, i have : i/O error alternatively on every rancher-nfs volume. 

For testing, i just launch two app (one on each host) and connect to it with shell and read in loop a single line file with sleep 1 second. I have i/o error sometimes on host 1 sometimes on host 2. To prevent i/o errors i need to delete app (and check rancher storage volume is well detach) and have only one host with rancher volumes attached.

Do you already have this issue ?

I also try to launch nfs-server with "host" network and target directly nfs-server host real ip in rancher nfs driver config. It work fine in this case. Maybe error is due to "managed" network layer in rancher.

By the way, when we use "host" network, due to   /etc/exports generated with * everybody can mount. Is there a way to limit access ?

Thanks in advance,
Feel free to ask me if you need more information.

**Comment by sjiveson** [comment]
Hey @gregori-goossens,

this isn't something I can easily test and not a scenario I'm familiar with (particularly Rancher volume drivers) unfortunately so I'm not sure I can help you with your biggest issue.

I did have a quick look through the docs and I wonder if you are using the `external: true` parameter? I'm short of time so perhaps this is a poor question.

On the plus side, I could probably make the permitted source value a variable (with * as the default) sometime this week.

**Comment by gregori-goossens** [comment]
Hi @sjiveson ,

thanks for your reply.
I understand that it's a very specific issue.
I will try to create an issue on rancher side. I think is a network layer communication issue.

If you have some time, it will be helpful for me to have a variable for permitted source.

Thanks again,

I will close this issue that not really related.

Gregori

**Comment by sjiveson** [comment]
Hey, you're welcome. I've added the ability to restrict sources via the PERMITTED environment variable.

**Comment by gregori-goossens** [comment]
Great !

Thanks a lot.
