### ISSUE TITLE
How to use this nfs server with windows clients ?

### ISSUE THREAD

**Issue by Roger53** [sjiveson/nfs-server-alpine#14]
Hi,

How do I connect a windows 10 pro client with standard NFS enabled ? I tried 6-arm and arm-latest.

Linux server and client work, with given command lines. (eg mount -v -o vers=4,loud IP:/ /tmp/nfs )

But how do I connect a Windows 10 pro NFS client ?
followed https://graspingtech.com/mount-nfs-share-windows-10 like
  mount -o anon \\IP\nfsshare Z:
  mount -o anon IP:/nfsshare Z:
 etc etc
Network Error - 53 : 	The network path was not found.

Can you help here ?

**Comment by sjiveson** [comment]
Hey Roger,

Sorry for taking so long to respond, is this still a problem?

Its probably a typo but I didn't see you use `\\` in your two example above?

I don't have W10 Pro to test which is problematic. 

My first port of call would be to try and establish if Windows firewall (or your AV firewall) is denying the traffic. Assuming you can ping the server, try something like http://www.portcheck-tool.com/ to check that your outbound traffic to the server is getting through on TCP port 2049.

If that works, let me know and I'll do some more digging.

**Comment by Roger53** [comment]
No worries Steven, no hurry, currently I use samba, but want higher speed, so trying nfs now.
Firewalls, : did not think about that, disabled all, but that is not the problem.

Yes typo : 
mount -o anon \IP\nfsshare Z: 
should be 
mount -o anon \\\IP\nfsshare Z: but that does not work  ( Strange in the github editor I now have 3 x \ )

Ok, so perhaps anyone else can help with the windows part?

So Steven, a pure linux question then : 

Linux server : 
docker run -d \
--privileged \
-v /dummy/nfs:/nfsshare \
-e SHARED_DIRECTORY=/nfsshare \
-p 2049:2049 \
itsthenetwork/nfs-server-alpine:9-arm
also tried 6-arm

On the linux client :
mount -v -o vers=4,loud 192.168.62.36:/ /tmp/nfs     
this works, "Is" shows the share contents and I can up/download at high speed

then an umount /tmp/nfs       :-)

mount -v -o vers=4,loud 192.168.62.36:/nfsshare /tmp/nfs
does not work, where I thought that the real sharename is nfsshare, and :/ is a wildcard like thing
So what is wrong in my thinking then ?

**Comment by Roger53** [comment]
Hmm, you use fsid=0
https://askubuntu.com/questions/35077/cannot-mount-nfs4-share-no-such-file-or-directory#50244
Ill do some more searching

**Comment by sjiveson** [comment]
Ahhhh. I didn't pick up on that, you are correct, there is no need to specify /nfsshare, as mentioned in the README:

> Due to the fsid=0 parameter set in the /etc/exports file, there's no need to specify the folder name when mounting from a client. For example, this works fine even though the folder being mounted and shared is /nfsshare:
> sudo mount -v 10.11.12.101:/ /some/where/here

**Comment by Roger53** [comment]
Ok Steven, well yeah, "not needed" vs "not possible" :-)

I am trying a native install here http://www.ubuntugeek.com/how-to-configure-nfs-server-and-client-configuration-on-ubuntu-16-04-xenial-xerus.html
and both windows / linux clients work, but the speed is far from what I expected, not mentioning the crashes. I need to change from Ubuntu develop 18 to LTS 16,  or 14, see if that helps

Difference with your solution in Windows : 
  C:\Users\admin>showmount -e <IP>
  RPC: Remote system errorRPC: Port mapper failure - RPC: Timed out.
Where the native install nicely shows what is shared and mounts.
This could be a problem :  Port 111 used with NFS, NIS, or any rpc-based service.
docker: Error response from daemon: driver failed programming external connectivity on endpoint quirky_hugle (472c88fd59650d51424e6b2cdddbc29997ce25260f4873fbcd22ba1e262aeae7): Error starting userland proxy: listen tcp 0.0.0.0:111: bind: address already in use.

I will try some alternatives, but at the end I want NFS in an alpine docker with second IP address and faster than Samba :-)

I will try to get it work in an Ubuntu container first, then try alpine later.

If you want, you can close this issue as there is no real issue when your target group is linux clients.

Thanks for your input so far.

**Comment by sjiveson** [comment]
OK, you're welcome.

You might want to check what NFS versions Windows supports. This container only supports v4 which doesn't use RPC. The rpcbind service is running though, but only to overcome a bug with IPv6 that was reported a while back.

You might be able to 'hack it' by running the container with host networking mode and/or removing `--no-udp --no-nfs-version 2 --no-nfs-version 3` where it appears in the nfsd.sh script and rebuilding the image.

**Comment by sjiveson** [comment]
No further response, closing.

**Comment by Roger53** [comment]
Ok Steven, I agree you closed.

I got side-tracked a bit with another solution, but that fails till now.

Thanks for your tips and in a few weeks, I will try them, hopefully I can get it to work, even-though this is pretty new ground for me :-).

**Comment by sjiveson** [comment]
Cool. Good luck and please do let me know if you find a solution. Cheers

**Comment by Roger53** [comment]
Hi Steven, Just to let you know that I will not continue with this, as I managed to get the full 100MByte/s using Samba on an arm device, so no need to search for alternatives anymore.
Thanks anyways.

**Comment by sjiveson** [comment]
OK, understandable and I'm glad you got it done, thanks for letting me know. Cheers
