### ISSUE TITLE
can you support nfs v2?

### ISSUE THREAD

**Issue by songqingkun** [sjiveson/nfs-server-alpine#2]
My u-boot only support nfs v2 and v3. can you support v2?

**Comment by sjiveson** [comment]
I've never managed to get v2 or v3 working with any consistency, at least where RancherOS is concerned (which is what this image was created with in mind). I'll see if I can dig out what I did as it looks like it might be useful for others, assuming my issue with that particular OS is unique to it.

**Comment by songqingkun** [comment]
thanks

**Comment by sjiveson** [comment]
Sorry it's taken so long. Everything is actually still in the entrypoint script (but commented out) if you have a look. Hopefully I get some time to build and test tomorrow.

**Comment by sjiveson** [comment]
Assuming there's no interest and closing.
