### ISSUE TITLE
Question: Is it possible to create more than one shared folder?

### ISSUE THREAD

**Issue by azizunsal** [sjiveson/nfs-server-alpine#20]
I think it is not possible to create multiple shared folder(`/path/to/share_1 /path/to/share_2`) in the current configuration. I wonder if there is some technical issues causing not to implement in that way. 

By the way thank you for this Docker image.

**Comment by sjiveson** [comment]
Hey Aziz, thank you.

Yes, its possible and relatively simple. However, optionally accommodating a varying number of shared folders (possibly with differing parameters) for different user needs becomes complicated.

In the short term you could easily duplicate the first line of confd/tmpl/exports.tmpl and change SHARED_DIRECTORY to, for instance SHARED_DIRECTORY_2, rebuild the image and feed in the additional variable.

I will look into adding this to the code here, with the caveat that other variables around sync, read-only etc. will have to be the same for all shares.

**Comment by azizunsal** [comment]
Hi Steven,
Thank you for your response. I will use your image because it's cleaner and readable when I compare it to the other existing NFS images. Maybe more advanced configurations can be added as you said.

**Comment by azizunsal** [comment]
Btw, I didn't notice that there was a closed [issue](https://github.com/sjiveson/nfs-server-alpine/issues/13) for the same question. Sorry..

**Comment by sjiveson** [comment]
No problem, I'm hoping I can use confd to accommodate this while keeping it clean and simple for those that don't want it.

**Comment by sjiveson** [comment]
FYI, I've got to this and the work is in branch **byebyeconfd** (which also removed use of confd) - hope to be done soon.

**Comment by sjiveson** [comment]
Hey. I've made some changes to help support this, please see the latest README.
