### ISSUE TITLE
Automatic build on Docker hub.

### ISSUE THREAD

**Issue by zsoerenm** [sjiveson/nfs-server-alpine#26]
Could you turn this into an automatic build on Docker Hub?
Automatic builds are more trustworthy than uploaded builds and get better search rankings.

**Comment by sjiveson** [comment]
Hey,

I'll look into this. Time is at a premium but if it looks like something I can do quickly, I'll do it.

**Comment by sjiveson** [comment]
Took a look and liked what I saw mostly but unfortunately, in order to set this up Docker Hub wants full read/write access to all my public and private repositories which I don't find acceptable. A real shame.
