### ISSUE TITLE
Suggestion: Support for ARM docker image. 

### ISSUE THREAD

**Issue by MayankTahil** [sjiveson/nfs-server-alpine#3]
I tested your dockerfile out on my bananapi Pro running armbian with the following base image : `hypriot/rpi-alpine`. It works well for me. Wonder if you'd be interested in branching the repository and updating the `Dockerfile`'s first line to `FROM hypriot/rpi-alpine` to support ARM based docker  hosts. I know I'd appreciate the docker image tag from your repo. 

Thanks!

**Comment by sjiveson** [comment]
Hey. Great idea. I've created an arm branch, added a new label in the Dockerfile to denote the branch, updated the README and also bumped the confd version to 0.14.0.

Built on a Pi and 6-arm and latest-arm image tags now available on Dockerhub.

**Comment by ulm0** [comment]
It'd be nice to have a multi-arch image using the manifest-tool, and aarch64 support as well, a Travis Pipeline can be created for this purpose, or even mirror this project on gitlab and use their CI.

**Comment by sjiveson** [comment]
Yeah, it would but its not something I have the time for. Cheers
