### ISSUE TITLE
documentation issue with READ_ONLY flag

### ISSUE THREAD

**Issue by salami738** [sjiveson/nfs-server-alpine#31]
Hi,

in the documentation on https://hub.docker.com/r/itsthenetwork/nfs-server-alpine:
`Adding -e READ_ONLY=true will cause the exports file to contain ro instead of rw, allowing only read access by clients.
`

But `READ_ONLY=false` also leads to a read only export.

Maybe you can fix the entrypoint script or add a notice to the documentation

greetings!

**Comment by sjiveson** [comment]
Hey,

Thank you. I'd obviously changed the logic somewhere to what it is now, which is far more efficient and forgot to update the README. Great spot, thank you and corrected.
