### ISSUE TITLE
Bug report: Cannot restart container "exportfs: duplicated export entries"

### ISSUE THREAD

**Issue by siaimes** [sjiveson/nfs-server-alpine#48]
![image](https://user-images.githubusercontent.com/34199488/140680828-13844e12-596e-4aeb-ba8b-1a079a8947fa.png)

![image](https://user-images.githubusercontent.com/34199488/140681086-69672b29-6c0b-40f0-84a3-2920bc1b8c24.png)

**Comment by siaimes** [comment]
Caused by this line:

https://github.com/sjiveson/nfs-server-alpine/blob/8dddf580ef7741971a87c38ef6099ebd9b12bc73/nfsd.sh#L40

This line will be added every time you restart, causing entries duplication.

**Comment by sjiveson** [comment]
PR merged, thank you.
